import { ICategoryDTO, IProductDTO } from '@/domain/types';

export const mockCategoriesDTO: ICategoryDTO[] = [
  { _id: '1', title: 'Biryani', icon_path: '/images/icon-biryani.png' },
  { _id: '2', title: 'Pizza', icon_path: '/images/icon-pizza.png' },
  { _id: '3', title: 'Burger', icon_path: '/images/icon-burger.png' },
  { _id: '4', title: 'Sandwich', icon_path: '/images/icon-pizza.png' },
];

export const mockProductsDTO: IProductDTO[] = [
  {
    _id: 'p1',
    category_id: '1',
    title: 'Hyderabadi Biryani',
    customer_rating: 4.8,
    total_reviews: 1050,
    distance_str: '2.5 km',
    delivery_time_str: '20 min delivery',
    price_usd: 7.50,
    calories_kcal: 450,
    diameter_cm: 15.05,
    desc: 'Hyderabadi biryani is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender meat, and fragrant basmati rice. originating from the vibrant city of the Hyaderabad in india, this is iconic dish...',
    image_path: '/images/hyderabadi.png',
  },
  {
    _id: 'p2',
    category_id: '1',
    title: 'Bombay Biryani',
    customer_rating: 4.5,
    total_reviews: 1320,
    distance_str: '3.5 km',
    delivery_time_str: '25 min delivery',
    price_usd: 8.50,
    calories_kcal: 380,
    diameter_cm: 15.05,
    desc: 'Bombay biryani is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner, mater and fragrant basmati rice. originating from the vibrant city of the Hyaderabad in india, this is iconic dish...',
    image_path: '/images/bombay.png',
  },
  {
    _id: 'p3',
    category_id: '2',
    title: 'onion capsicum pizza',
    customer_rating: 4.9,
    total_reviews: 1550,
    distance_str: '2.5 km',
    delivery_time_str: '20 min delivery',
    price_usd: 10.50,
    calories_kcal: 480,
    diameter_cm: 18.05,
    desc: 'Onion capsicum pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender onion and capsicum and tragrant pizza base. originating from the vibrant city of the Hyaderabad in India, this is iconic dish...',
    image_path: '/images/pizza-onion-v2.png',
  },
  {
    _id: 'p4',
    category_id: '2',
    title: 'Panner pizza',
    customer_rating: 4.2,
    total_reviews: 1130,
    distance_str: '3.5 km',
    delivery_time_str: '25 min delivery',
    price_usd: 9.50,
    calories_kcal: 460,
    diameter_cm: 12.05,
    desc: 'Panner and mater pizza is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner, mater and tragrant pizza base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish...',
    image_path: '/images/pizza-panner.png',
  },
  {
    _id: 'p5',
    category_id: '3',
    title: 'Veg Burger',
    customer_rating: 4.2,
    total_reviews: 1130,
    distance_str: '2.5 km',
    delivery_time_str: '20 min delivery',
    price_usd: 12.50,
    calories_kcal: 560,
    diameter_cm: 6.05,
    desc: 'Veg burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender aalu tiki and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish...',
    image_path: '/images/burger-veg.png',
  },
  {
    _id: 'p6',
    category_id: '3',
    title: 'Paneer Burger',
    customer_rating: 4.6,
    total_reviews: 1230,
    distance_str: '3.5 km',
    delivery_time_str: '25 min delivery',
    price_usd: 8.50,
    calories_kcal: 460,
    diameter_cm: 4.00,
    desc: 'Panner burger is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu tiki and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish...',
    image_path: '/images/burger-paneer.png',
  },
  {
    _id: 'p7',
    category_id: '4',
    title: 'Veg Sandwhic',
    customer_rating: 4.6,
    total_reviews: 1230,
    distance_str: '2.5 km',
    delivery_time_str: '20 min delivery',
    price_usd: 7.50,
    calories_kcal: 460,
    diameter_cm: 4.00,
    desc: 'Veg sandwhic is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish...',
    image_path: '/images/sandwich-veg.png',
  },
  {
    _id: 'p8',
    category_id: '4',
    title: 'Potato Sandwhic',
    customer_rating: 4.6,
    total_reviews: 1343,
    distance_str: '3.5 km',
    delivery_time_str: '25 min delivery',
    price_usd: 6.50,
    calories_kcal: 460,
    diameter_cm: 4.00,
    desc: 'Potato sandwhic is a culinary masterpiece that tantalizes the senses with its aromatic spices, tender panner,aalu and tamato,other and tragrant burger base. originating from the vibrant city of the Hyaderabad in india, this is iconic dish...',
    image_path: '/images/sandwich-potato.png',
  }
];
